#!/bin/sh

clang++ -I/usr/local/include  -fPIC -fvisibility-inlines-hidden -fno-exceptions \
-Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -Wextra -Wno-unused-parameter \
-Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default \
-Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O0 \
-c -emit-llvm -o temp.bc $1
llvm-dis temp.bc -o $2
