function Tc(){return function(a){return a}}function q(){return function(){}}function Uc(a){return function(b){this[a]=b}}function Vc(a){return function(){return a}}
var Wc=typeof Object.defineProperties==m?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},Xc=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a}(this),Yc=function(){Yc=q();Xc.Symbol||(Xc.Symbol=Zc)},Zc=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}(),ad=function(){Yc();var a=Xc.Symbol.iterator;a||(a=Xc.Symbol.iterator=Xc.Symbol("iterator"));typeof Array.prototype[a]!=
m&&Wc(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $c(this)}});ad=q()},$c=function(a){var b=0;return bd(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})},bd=function(a){ad();a={next:a};a[Xc.Symbol.iterator]=function(){return this};return a},cd=function(a){ad();var b=a[Symbol.iterator];return b?b.call(a):$c(a)},dd=function(a,b){if(b){var c=Xc;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&
null!=b&&Wc(c,a,{configurable:!0,writable:!0,value:b})}};
dd("Promise",function(a){function b(){this.a=null}function c(a){switch(typeof a){case Xb:return null!=a;case m:return!0;default:return!1}}function d(a){return a instanceof f?a:new f(function(b){b(a)})}if(a)return a;b.prototype.b=function(a){null==this.a&&(this.a=[],this.f());this.a.push(a)};b.prototype.f=function(){var a=this;this.c(function(){a.l()})};var e=Xc.setTimeout;b.prototype.c=function(a){e(a,0)};b.prototype.l=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;++b){var c=
a[b];a[b]=null;try{c()}catch(n){this.g(n)}}}this.a=null};b.prototype.g=function(a){this.c(function(){throw a;})};var f=function(a){this.b=0;this.c=void 0;this.a=[];var b=this.f();try{a(b.resolve,b.reject)}catch(l){b.reject(l)}};f.prototype.f=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.F),reject:a(this.g)}};f.prototype.F=function(a){a===this?this.g(new TypeError("A Promise cannot resolve to itself")):a instanceof f?this.G(a):c(a)?this.C(a):
this.l(a)};f.prototype.C=function(a){var b=void 0;try{b=a.then}catch(l){this.g(l);return}typeof b==m?this.H(b,a):this.l(a)};f.prototype.g=function(a){this.o(2,a)};f.prototype.l=function(a){this.o(1,a)};f.prototype.o=function(a,b){if(0!=this.b)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.b);this.b=a;this.c=b;this.A()};f.prototype.A=function(){if(null!=this.a){for(var a=0;a<this.a.length;++a)g.b(this.a[a]);this.a=null}};var g=new b;f.prototype.G=function(a){var b=
this.f();a.Ha(b.resolve,b.reject)};f.prototype.H=function(a,b){var c=this.f();try{a.call(b,c.resolve,c.reject)}catch(n){c.reject(n)}};f.prototype.then=function(a,b){function c(a,b){return typeof a==m?function(b){try{d(a(b))}catch(qb){e(qb)}}:b}var d,e,g=new f(function(a,b){d=a;e=b});this.Ha(c(a,d),c(b,e));return g};f.prototype.catch=function(a){return this.then(void 0,a)};f.prototype.Ha=function(a,b){function c(){switch(d.b){case 1:a(d.c);break;case 2:b(d.c);break;default:throw Error("Unexpected state: "+
d.b);}}var d=this;null==this.a?g.b(c):this.a.push(c)};f.resolve=d;f.reject=function(a){return new f(function(b,c){c(a)})};f.race=function(a){return new f(function(b,c){for(var e=cd(a),f=e.next();!f.done;f=e.next())d(f.value).Ha(b,c)})};f.all=function(a){var b=cd(a),c=b.next();return c.done?d([]):new f(function(a,e){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,d(c.value).Ha(f(g.length-1),e),c=b.next();while(!c.done)})};return f});
