./ac_js_compiler proxy.json | tail -3
./ac_js_compiler proxy.tpl.json | tail -3
./ac_js_compiler proxy_banner.json | tail -3
./ac_js_compiler proxy_banner_mediation.json | tail -3
./ac_js_compiler proxy_device_linked.json | tail -3
./ac_js_compiler proxy_device_not_linked.json | tail -3
./ac_js_compiler proxy_drx_banner_mediation.json | tail -3
./ac_js_compiler proxy_drx_banner_mediation_nofill.json | tail -3
./ac_js_compiler proxy_drx_interstitial_mediation.json | tail -3
./ac_js_compiler proxy_drx_native_mediation.json | tail -3
./ac_js_compiler proxy_drx_rewarded_video_mediation.json | tail -3
./ac_js_compiler proxy_head_js.json | tail -3
./ac_js_compiler proxy_immersive_mode.json | tail -3
./ac_js_compiler proxy_macro.json | tail -3
./ac_js_compiler proxy_mopub.json | tail -3
./ac_js_compiler proxy_noads.json | tail -3
./ac_js_compiler proxy_omid_drx_rewarded_video.json | tail -3
./ac_js_compiler proxy_one_color.json | tail -3
./ac_js_compiler proxy_onead.json | tail -3
./ac_js_compiler proxy_recursive_banner.json | tail -3
./ac_js_compiler proxy_video.json | tail -3
