../llvmify ../ac_ast_base_nodes.cc 
../llvmify ../ac_ast_builder.cc
../llvmify ../ac_ast_error_nodes.cc
../llvmify ../ac_ast_expression_nodes.cc
../llvmify ../ac_ast_func_class_nodes.cc
../llvmify ../ac_ast_llvm_codegen.cc
../llvmify ../ac_ast_member_ref_nodes.cc
../llvmify ../ac_ast_object_nodes.cc
../llvmify ../ac_ast_statement_nodes.cc
../llvmify ../ac_ast_variant_node.cc
../llvmify ../ac_ast_visitable.cc
../llvmify ../ac_js_compiler.cc
../llvmify ../ac_js_constants.cc
../llvmify ../ac_js_declaration_parser.cc
../llvmify ../ac_js_expression_parser.cc
../llvmify ../ac_js_initializer_parser.cc
../llvmify ../ac_js_misc_parser.cc
../llvmify ../ac_js_parser.cc
../llvmify ../ac_js_statement_parser.cc
../llvmify ../ac_lex_comments.cc
../llvmify ../ac_lex_datatypes.cc
../llvmify ../ac_lex_identifier.cc
../llvmify ../ac_lex_numbers.cc
../llvmify ../ac_lex_punctuators.cc
../llvmify ../ac_lex_regex.cc
../llvmify ../ac_lex_scanners.cc
../llvmify ../ac_lex_state.cc
../llvmify ../ac_lex_string.cc
../llvmify ../ac_lex_token_pos.cc
../llvmify ../ac_lex_util.cc
../llvmify ../ac_logger.cc
../llvmify ../ac_vm_jsfunction.cc
../llvmify ../ac_vm_jsobject.cc
../llvmify ../ac_vm_jsprimitives.cc
../llvmify ../ac_vm_jsvalue.cc
../llvmify ../argc_test.cc
../llvmify ../driver.cc
../llvmify ../jsprimitive1.cc
../llvmify ../jsvalue1.cc
../llvmify ../jsvalue_test.cc
../llvmify ../reference.cc
../llvmify ../script1.cc
../llvmify ../testsize.cc
