../llvmify ../ac_ast_base_nodes.cc ../ac_ast_base_nodes.ll
../llvmify ../ac_ast_builder.cc ../ac_ast_builder.ll
../llvmify ../ac_ast_error_nodes.cc ../ac_ast_error_nodes.ll
../llvmify ../ac_ast_expression_nodes.cc ../ac_ast_expression_nodes.ll
../llvmify ../ac_ast_func_class_nodes.cc ../ac_ast_func_class_nodes.ll
../llvmify ../ac_ast_llvm_codegen.cc ../ac_ast_llvm_codegen.ll
../llvmify ../ac_ast_member_ref_nodes.cc ../ac_ast_member_ref_nodes.ll
../llvmify ../ac_ast_object_nodes.cc ../ac_ast_object_nodes.ll
../llvmify ../ac_ast_statement_nodes.cc ../ac_ast_statement_nodes.ll
../llvmify ../ac_ast_variant_node.cc ../ac_ast_variant_node.ll
../llvmify ../ac_ast_visitable.cc ../ac_ast_visitable.ll
../llvmify ../ac_js_compiler.cc ../ac_js_compiler.ll
../llvmify ../ac_js_constants.cc ../ac_js_constants.ll
../llvmify ../ac_js_declaration_parser.cc ../ac_js_declaration_parser.ll
../llvmify ../ac_js_expression_parser.cc ../ac_js_expression_parser.ll
../llvmify ../ac_js_initializer_parser.cc ../ac_js_initializer_parser.ll
../llvmify ../ac_js_misc_parser.cc ../ac_js_misc_parser.ll
../llvmify ../ac_js_parser.cc ../ac_js_parser.ll
../llvmify ../ac_js_statement_parser.cc ../ac_js_statement_parser.ll
../llvmify ../ac_lex_comments.cc ../ac_lex_comments.ll
../llvmify ../ac_lex_datatypes.cc ../ac_lex_datatypes.ll
../llvmify ../ac_lex_identifier.cc ../ac_lex_identifier.ll
../llvmify ../ac_lex_numbers.cc ../ac_lex_numbers.ll
../llvmify ../ac_lex_punctuators.cc ../ac_lex_punctuators.ll
../llvmify ../ac_lex_regex.cc ../ac_lex_regex.ll
../llvmify ../ac_lex_scanners.cc ../ac_lex_scanners.ll
../llvmify ../ac_lex_state.cc ../ac_lex_state.ll
../llvmify ../ac_lex_string.cc ../ac_lex_string.ll
../llvmify ../ac_lex_token_pos.cc ../ac_lex_token_pos.ll
../llvmify ../ac_lex_util.cc ../ac_lex_util.ll
../llvmify ../ac_logger.cc ../ac_logger.ll
../llvmify ../ac_vm_jsfunction.cc ../ac_vm_jsfunction.ll
../llvmify ../ac_vm_jsobject.cc ../ac_vm_jsobject.ll
../llvmify ../ac_vm_jsprimitives.cc ../ac_vm_jsprimitives.ll
../llvmify ../ac_vm_jsvalue.cc ../ac_vm_jsvalue.ll
../llvmify ../argc_test.cc ../argc_test.ll
../llvmify ../driver.cc ../driver.ll
../llvmify ../jsprimitive1.cc ../jsprimitive1.ll
../llvmify ../jsvalue1.cc ../jsvalue1.ll
../llvmify ../jsvalue_test.cc ../jsvalue_test.ll
../llvmify ../reference.cc ../reference.ll
../llvmify ../script1.cc ../script1.ll
../llvmify ../testsize.cc ../testsize.ll
